# Resolve directories relative to this script.
set SCRIPT_DIR [file normalize [file dirname [info script]]]
set ROOT       [file normalize "$SCRIPT_DIR/../.."]
set PROJECT_DIR "$SCRIPT_DIR/project_nofpu"
set STIM_FILE   "$ROOT/regression_tests/hello/build/vectors/stim.txt"

# Stop immediately if the generated source script is missing.
if {![file exists "$SCRIPT_DIR/generated/compile.tcl"]} {
    error "Generated source script is missing."
}

# Stop immediately if the hello stimulus is missing.
if {![file exists $STIM_FILE]} {
    error "Hello stimulus is missing: $STIM_FILE"
}

# Remove only the previous generated Vivado project through create_project -force.
create_project pulp_xsim_nofpu "$PROJECT_DIR" -force

# Select an installed FPGA part for behavioral simulation.
set AVAILABLE_PARTS [get_parts]
if {[llength $AVAILABLE_PARTS] == 0} {
    error "No supported Vivado device parts are installed."
}
set SELECTED_PART [lindex $AVAILABLE_PARTS 0]
set_property part $SELECTED_PART [current_project]
puts "XSIM-INFO: Selected simulation part: $SELECTED_PART"

# Configure the project for SystemVerilog simulation.
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]

# Enable Xilinx Parameterized Macro memory models.
set_property XPM_LIBRARIES {XPM_MEMORY} [current_project]

# Add the PULP RTL and testbench files generated by Bender.
source "$SCRIPT_DIR/generated/compile.tcl"

# Add simulation-only models omitted by the Bender Vivado backend.
source "$SCRIPT_DIR/generated/extra_sim_sources.tcl"

# Define XSIM for simulator-specific RTL compatibility paths.
foreach FILESET_NAME {sources_1 sim_1} {
    set CURRENT_DEFINES [get_property verilog_define [get_filesets $FILESET_NAME]]
    if {[lsearch -exact $CURRENT_DEFINES XSIM] < 0} {
        lappend CURRENT_DEFINES XSIM
        set_property verilog_define $CURRENT_DEFINES [get_filesets $FILESET_NAME]
    }
}

# Let Vivado determine package and module compilation order.
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1

# Select the complete PULP testbench as simulation top.
set_property top tb_pulp [get_filesets sim_1]
set_property top_auto_set 0 [get_filesets sim_1]

# Configure the same important parameters used by the QuestaSim hello test.
set_property generic {
    LOAD_L2=JTAG
    RISCY_FPU=0
    BAUDRATE=115200
} [get_filesets sim_1]

# Preserve internal signals for waveform debugging.
set_property xsim.elaborate.debug_level off [get_filesets sim_1]
# Limit elaboration parallelism to reduce peak memory usage.
set_property xsim.elaborate.mt_level off [get_filesets sim_1]

# Pass the entry point and absolute stimulus path to tb_pulp.
set XSIM_OPTIONS [format \
    "-testplusarg ENTRY_POINT=1c008080 -testplusarg stimuli=%s" \
    $STIM_FILE]

# Use named arguments because the property value starts with a dash.
set_property \
    -name {xsim.simulate.xsim.more_options} \
    -value $XSIM_OPTIONS \
    -objects [get_filesets sim_1]

# Set a runtime longer than the successful QuestaSim execution.
set_property xsim.simulate.runtime 6ms [get_filesets sim_1]

# Compile, elaborate and open the behavioral simulation.
# Ignore concurrent assertions unsupported by Vivado 2019.1.
set_property \
    -name {xsim.elaborate.xelab.more_options} \
    -value {-ignore_assertions} \
    -objects [get_filesets sim_1]

launch_simulation -simset sim_1 -mode behavioral

# Record the most important top-level testbench signals.
foreach SIGNAL {
    /tb_pulp/s_clk_ref
    /tb_pulp/w_clk_ref
    /tb_pulp/s_rst_n
    /tb_pulp/w_rst_n
    /tb_pulp/s_bootsel
    /tb_pulp/w_bootsel
    /tb_pulp/s_tck
    /tb_pulp/s_tms
    /tb_pulp/s_tdi
    /tb_pulp/s_tdo
    /tb_pulp/w_uart_rx
    /tb_pulp/w_uart_tx
    /tb_pulp/exit_status
} {
    if {[catch {log_wave $SIGNAL} MESSAGE]} {
        puts "XSIM-WAVE-SKIP: $SIGNAL"
    }
}

# Execute the test until completion or the six-millisecond limit.
run 6 ms

# Report the final simulation time.
puts "XSIM-INFO: Simulation stopped at [current_time]"

# Save the project state and close Vivado in batch mode.
close_sim
save_project_as pulp_xsim_nofpu "$PROJECT_DIR" -force
close_project
exit
